name: build mac middleware
on: workflow_dispatch
jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      
      - name: Create output directories
        run: mkdir -p bundle/GhidraDeepLinksHandler.app/Contents/MacOS && mkdir -p bundle/GhidraDeepLinksHandler.app/Contents/Resources
        working-directory: os/mac

      - name: Copy Info.plist
        run: cp Info.plist bundle/GhidraDeepLinksHandler.app/Contents/Info.plist
        working-directory: os/mac

      - name: Copy icon
        run: cp ghidra-deep-links-logo.icns bundle/GhidraDeepLinksHandler.app/Contents/Resources/ghidra-deep-links-logo.icns
        working-directory: os/mac

      - name: Build x86_64
        run: clang -target x86_64-apple-macos10.12 -framework Cocoa -lobjc *.m -o main-x86_64
        working-directory: os/mac
      
      - name: Build ARM64
        run: clang -target arm64-apple-macos11 -framework Cocoa -lobjc *.m -o main-arm64
        working-directory: os/mac

      - name: Package universal binary
        run: lipo -create -output bundle/GhidraDeepLinksHandler.app/Contents/MacOS/main main-x86_64 main-arm64
        working-directory: os/mac

      - name: Create dmg
        run: hdiutil create /tmp/tmp.dmg -ov -volname "DeeplinksHandlerInstall" -fs HFS+ -srcfolder os/mac/bundle
      
      - name: Finalise dmg
        run: hdiutil convert /tmp/tmp.dmg -format UDZO -o GhidraDeepLinksHandler.dmg

      - name: Export artifacts 2
        uses: actions/upload-artifact@v4
        with:
          name: GhidraDeepLinksHandler
          path: GhidraDeepLinksHandler.dmg
